version: "3.3"
services:
  python:
    container_name: "itsclassifier_python_api"
    build:
      context: ./python
    environment:
      - FLASK_APP=app.py
      - FLASK_PORT=8080
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./python:/python
  react:
    container_name: "itsclassifier_react"
    build:
      context: ./client
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./client/src:/app/src